version: "3"

services:
  postgres:
    container_name: gaspar_psql
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/Users/pjacobs/docker/volumes/postgres
    environment:
      POSTGRES_USER: gaspar
      POSTGRES_PASSWORD: dev123
      PGDATA: /Users/pjacobs/docker/volumes/postgres
  gaspar:
    container_name: gaspar_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${GASPAR_PORT}:8080
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data: