# build
FROM maven:3.8.1-openjdk-16 AS MAVEN_BUILD
WORKDIR /package
COPY . .
RUN mvn clean package -Dmaven.test.skip=true

# run
FROM eclipse-temurin:16.0.2_7-jdk-focal
WORKDIR /app
COPY --from=MAVEN_BUILD /package/target/gaspar.jar gaspar.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","gaspar.jar"]