spring:
    profiles:
        active: dev
    application:
        name: gaspar
    main:
        web-application-type: reactive
    r2dbc:
        url: ${env.GASPAR_DB_URI}
        username: ${env.GASPAR_DB_USERNAME}
        password: ${env.GASPAR_DB_PASSWORD}

gaspar:
    api-version: 1


